on:
  push:
    branches:
      - main
jobs:
  deploy:
    name: Build and Push to GCP
    runs-on: ubuntu-latest
    
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:  
    - name: Checkout
      uses: actions/checkout@v3

    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v1'
      with:
          credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
          service_account: 'cloud-run-invoker@starry-sylph-383122.iam.gserviceaccount.com'
    
    - uses: google-github-actions/setup-gcloud@1bee7de035d65ec5da40a31f8589e240eba8fde5
      with:
          project_id: ${{ secrets.PROJECT_ID }}

    - name: Build Docker Image
      run: docker build -t webserver:latest .
      
    - name: Test with pytest inside Docker
      run: docker run webserver:latest pytest
    
    - name: Configure Docker Client 
      run: |-
        gcloud auth configure-docker --quiet

    - name: Push Docker Image to Container Registry (GCR)
      run: |-
        docker tag webserver:latest gcr.io/starry-sylph-383122/webserver:latest
        docker push gcr.io/starry-sylph-383122/webserver:latest

  
    - id: 'deploy'
      name: 'Deploy Docker Image to Cloud Run'
      uses: 'google-github-actions/deploy-cloudrun@v1'
      with:
        service: 'nice-web'
        image: 'gcr.io/starry-sylph-383122/webserver:latest'
        region: 'us-central1'
        #

